server:
  port: 9999               #https端口
  http:
    port: 9100              #http端口
  ssl:
    key-store: classpath:zomkc.cn.jks
    key-store-password:
    key-store-type: JKS
    enabled: true
spring:
  application:
    #应用的名称
    name: webVCS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /Page/
      suffix: .jsp